repo_url: https://github.com/flanksource/canary-checker/
repo_name: Canary Checker
site_name: Canary Checker
theme:
  logo: ./images/cc-white.svg
  favicon: ./images/cc-blue.svg
  name: material
  palette:
  - media: '(prefers-color-scheme: light)'
    scheme: default
    primary: indigo
    accent: light-blue
    toggle:
      icon: material/lightbulb
      name: Switch to light mode
  - media: '(prefers-color-scheme: dark)'
    scheme: slate
    primary: indigo
    accent: light-blue
    toggle:
      icon: material/lightbulb-outline
      name: Switch to dark mode
  features:
    - content.tabs.link
    - search.suggest
    - search.highlight
    # - navigation.instant
    # - navigation.sections
    # - navigation.tracking
    # - navigation.expand
    # - navigation.top
markdown_extensions:
  - admonition
  - fenced_code
  - pymdownx.smartsymbols
  - toc:
      permalink: False
      anchorlink: True
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.tabbed
  - codehilite:
      linenums: true
nav:
  - Introduction:
    - Overview:  ./index.md
  - Tutorials: 
    - Getting Started: ./tutorials/getting-started.md
    - Contributing: ./tutorials/dev-guide.md
  - Installation:
    - Install CLI: ./run.md
    - Install on Standalone Server: ./server.md
    - Install Kubernetes Operator: ./operator.md
  - Reference:
    - Checks:
      - Cloudwatch: ./reference/checks/cloudwatch.md
      - ConfigDB: ./reference/checks/configdb.md
      - Containerd Pull: ./reference/checks/containerd-pull.md
      - Containerd Push: ./reference/checks/containerd-push.md
      - DNS: ./reference/checks/dns.md
      - Docker Pull: ./reference/checks/docker-pull.md
      - Docker Push: ./reference/checks/docker-push.md
      - EC2: ./reference/checks/ec2.md
      - Elasticsearch: ./reference/checks/elasticsearch.md
      - Exec: ./reference/checks/exec.md
      - GCSBucket: ./reference/checks/gcs-bucket.md
      - GCS Database Backup: ./reference/checks/gcs-database-backup.md
      - Helm: ./reference/checks/helm.md
      - HTTP: ./reference/checks/http.md
      - ICMP: ./reference/checks/icmp.md
      - JMeter: ./reference/checks/jmeter.md
      - JUnit: ./reference/checks/junit.md
      - Kubernetes: ./reference/checks/kubernetes.md
      - LDAP: ./reference/checks/ldap.md
      - Mongo: ./reference/checks/mongo.md
      - MsSql: ./reference/checks/mssql.md
      - MySQL: ./reference/checks/mysql.md
      - Namespace: ./reference/checks/namespace.md
      - Pod: ./reference/checks/pod.md
      - Postgres: ./reference/checks/postgres.md
      - Prometheus: ./reference/checks/prometheus.md
      - Redis: ./reference/checks/redis.md
      - Restic: ./reference/checks/restic.md
      - S3 Bucket: ./reference/checks/s3-bucket.md
      - S3: ./reference/checks/s3.md
      - SFTP: ./reference/checks/sftp.md
      - SMB / CIFS: ./reference/checks/smb.md
    - Topology:
      - Common:
        - Kubernetes Cluster: ./topology/common/kubernetes-cluster.md
      
